namespace RunicMagic.Database;

public record EntityData(
    Guid Id,
    long TypeId,
    string Label,
    long X,
    long Y,
    long Width,
    long Height,
    bool HasAgency,
    long Weight,
    long Strength,
    bool IsTranslucent = false,
    double Angle = 0,
    long? MaxHitPoints = null,
    long? CurrentHitPoints = null,
    long? MaxCharge = null,
    long? CurrentCharge = null,
    string[]? InscriptionTexts = null,
    long MaxStructuralIntegrity = 1000,
    long CurrentStructuralIntegrity = 1000,
    double DragCoefficient = 0.0,
    double AngularDragCoefficient = 0.0,
    AIData? AIData = null,
    double? LocomotionEfficiency = null);
