namespace RunicMagic.Database;

public record EntityData(
    Guid Id,
    long TypeId,
    string Label,
    long X,
    long Y,
    long Width,
    long Height,
    bool HasAgency,
    long Weight,
    long Strength,
    bool IsTranslucent,
    double Facing,
    long? MaxHitPoints,
    long? CurrentHitPoints,
    long? MaxCharge,
    long? CurrentCharge,
    string[]? InscriptionTexts,
    long MaxStructuralIntegrity,
    long CurrentStructuralIntegrity,
    double DragCoefficient,
    double AngularDragCoefficient,
    double GroundFrictionCoefficient,
    AIData? AIData,
    double? LocomotionEfficiency);
