<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RunicMagic.Database\RunicMagic.Database.csproj" />
    <ProjectReference Include="..\RunicMagic.View\RunicMagic.View.csproj" />
    <ProjectReference Include="..\RunicMagic.World\RunicMagic.World.csproj" />
  </ItemGroup>

</Project>
